version: '3.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB='api'
      - POSTGRES_USER='api-platform'
      - POSTGRES_PASSWORD='!ChangeMe!'
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
  php:
    build:
      context: .
      target: api_php
    depends_on:
      - db
    volumes:
      - ./:/srv/api
      - ./docker/php/conf.d/dev.ini:/usr/local/etc/php/conf.d/api.ini
  api:
    build:
      context: .
      target: api_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - "8082:80"